"""
MiniSOC Alert Model

Defines the structure used to represent a security alert
generated by the Detection Engine.
"""

from dataclasses import dataclass, field
from datetime import datetime

from minisoc.models.event import EventSchema


@dataclass
class Alert:
    """
    Represents a security alert generated by a detection rule.

    An alert contains both:
    - Detection metadata
    - Evidence in the form of contributing events
    """

    # Detection metadata
    timestamp: datetime
    rule_id: str
    severity: str
    alert_type: str
    description: str

    # Context
    source_ip: str | None = None
    destination_ip: str | None = None
    user: str | None = None

    # Detection time window
    first_seen: datetime | None = None
    last_seen: datetime | None = None

    # Evidence
    events: list[EventSchema] = field(default_factory=list)